### ISSUE TITLE
Process for integration with Prolific

### ISSUE THREAD

**Issue by matthewolckers** [friedrichgeiecke/interviews#1]
Thanks so much for creating this simple but powerful platform. And awesome work on validating the usefulness. The local installation worked well. 

I am interested in knowing your setup for including the platform in a workflow with Prolific. 

1. Did you host the app on Streamlit Cloud?
2. Did you use a custom username and password for each respondent?
3. If yes how did share the usernames and passwords with the respondents?
4. Were the Prolific users directed to a survey platform first (eg. Qualtrics) and how did you match the interview transcripts to their survey responses?
5. Were there problems you ran into or common pitfalls you could share?

**Comment by friedrichgeiecke** [comment]
Hi,

Thanks for your questions! Please find the answers here.

1. For the paper, we hosted the app on Azure App Service. I could add a brief explanation to the repository on how to host the app there as an example.
2. Yes, we created a list of usernames and passwords and shared them with respondents.
3. In Prolific, there is an option to share user credentials.
4. Exactly, we used Qualtrics for additional survey questions and included a link to the web app in the survey. Participants received their login details through Prolific.
5. None that come to mind at the moment, but if you have any further questions, feel free to post them here.

Best wishes,

**Comment by matthewolckers** [comment]
Thanks for the feedback. The note on how you used Azure App service would be very helpful.
